Validate certificate via root CA
bosch-io/iot-things-examples pull request #14
Opened 2018-09-03 05:35 UTC by pho-enix

2018-09-03 09:21 UTC, Yannic92 requested changes
Looks good to me.
Tested it and it works. 
Just the two naming issues should be fixed.

Thank you for this PR! 👍

2018-09-03 09:21 UTC, Yannic92 commented on octopus-hub-things-example/src/main/octopus/octopus-mqtt/octopus.cpp
> +void Octopus::initBno280() {
I guess this should be initBme280?

2018-09-03 09:21 UTC, Yannic92 commented on octopus-hub-things-example/src/main/octopus/octopus-mqtt/octopus.cpp
> +  Printer::printMsg("Octopus", "Initializing BNO280: ");
Here again BME280

2018-09-06 13:22 UTC, Yannic92 commented
Targets Issue #13

2018-09-07 05:55 UTC, pho-enix commented
Naming issues resolved. Furthermore resolved the "Sensor reading failure" issue.

2018-09-07 08:12 UTC, Yannic92 approved these changes

2018-09-07 08:13 UTC, Yannic92 requested changes

2018-09-07 08:13 UTC, Yannic92 commented on octopus-hub-things-example/src/main/octopus/octopus-mqtt/octopus.cpp
> +    bme280Ready = true;
I think this should be bme680Ready?

2018-09-07 08:13 UTC, Yannic92 commented on octopus-hub-things-example/src/main/octopus/octopus-mqtt/octopus.cpp
> +    bme280Ready = false;
I think this should be bme680Ready?

2018-09-07 08:22 UTC, Yannic92 approved these changes

2018-09-07 08:30 UTC, merged